"""Rewrite admin.ts completely with video support"""

import sys
from pathlib import Path


def find_root():
    for c in [Path("."), Path("Learno"), Path("Learno MVP"),
              Path("Learno MVP v1"), Path("Learno MVP v1 - Copy")]:
        if (c / "package.json").exists() and (c / "server").exists():
            return c.resolve()
    p = Path(".").resolve()
    if (p / "package.json").exists() and (p / "server").exists():
        return p
    print("ERROR: Cannot find project root.")
    sys.exit(1)


def main():
    base = find_root()
    print("Project: " + str(base))

    lines = []
    lines.append("import { Router, Request, Response } from 'express';")
    lines.append("import { z } from 'zod';")
    lines.append("import mysql from 'mysql2/promise';")
    lines.append("import { pool } from '../db';")
    lines.append("import { requireAdmin } from '../middleware/requireAuth';")
    lines.append("import { logger } from '../utils/logger';")
    lines.append("")
    lines.append("const router = Router();")
    lines.append("")
    lines.append("function safeSkills(val: any): string[] {")
    lines.append("  if (!val) return [];")
    lines.append("  if (Array.isArray(val)) return val as string[];")
    lines.append("  if (typeof val === 'string') {")
    lines.append("    const s = val.trim();")
    lines.append("    if (!s) return [];")
    lines.append("    if (s.startsWith('[')) { try { return JSON.parse(s); } catch {} }")
    lines.append("    return s.split(',').map((x: string) => x.trim()).filter(Boolean);")
    lines.append("  }")
    lines.append("  return [];")
    lines.append("}")
    lines.append("")
    lines.append("router.get('/stats', requireAdmin, async (_req: Request, res: Response) => {")
    lines.append("  try {")
    lines.append("    const queries = await Promise.allSettled([")
    lines.append("      pool.execute('SELECT COUNT(*) as count FROM users'),")
    lines.append("      pool.execute('SELECT COUNT(*) as count FROM users WHERE is_onboarded=1'),")
    lines.append("      pool.execute('SELECT COUNT(*) as count FROM tasks'),")
    lines.append("      pool.execute('SELECT COUNT(*) as count FROM test_attempts WHERE status=\"completed\"'),")
    lines.append("      pool.execute('SELECT COUNT(*) as count FROM study_plans'),")
    lines.append("      pool.execute('SELECT COUNT(*) as count FROM ai_usage WHERE DATE(created_at)=CURDATE()'),")
    lines.append("    ]);")
    lines.append("    const g = (r: any) => r.status === 'fulfilled' ? (r.value[0] as any[])[0]?.count || 0 : 0;")
    lines.append("    return res.json({ success: true, data: {")
    lines.append("      totalUsers: g(queries[0]), onboardedUsers: g(queries[1]),")
    lines.append("      totalTasks: g(queries[2]), completedTests: g(queries[3]),")
    lines.append("      studyPlans: g(queries[4]), aiRequestsToday: g(queries[5]),")
    lines.append("    }});")
    lines.append("  } catch (err) {")
    lines.append("    logger.error('Admin stats:', err);")
    lines.append("    return res.status(500).json({ success: false, error: 'Failed to fetch stats.' });")
    lines.append("  }")
    lines.append("});")
    lines.append("")
    lines.append("router.get('/users', requireAdmin, async (req: Request, res: Response) => {")
    lines.append("  try {")
    lines.append("    const { page = '1', limit = '20' } = req.query;")
    lines.append("    const offset = (parseInt(String(page), 10) - 1) * parseInt(String(limit), 10);")
    lines.append("    const [rows] = await pool.execute(")
    lines.append("      'SELECT u.id, u.email, u.role, u.is_onboarded, u.created_at, sp.full_name FROM users u LEFT JOIN student_profiles sp ON sp.user_id=u.id ORDER BY u.created_at DESC LIMIT ' + parseInt(String(limit), 10) + ' OFFSET ' + offset")
    lines.append("    ) as any[];")
    lines.append("    return res.json({ success: true, data: (Array.isArray(rows) ? rows : []).map((u: any) => ({")
    lines.append("      id: u.id, email: u.email, role: u.role,")
    lines.append("      isOnboarded: Boolean(u.is_onboarded), fullName: u.full_name, createdAt: u.created_at,")
    lines.append("    }))});")
    lines.append("  } catch (err) {")
    lines.append("    logger.error('Admin users:', err);")
    lines.append("    return res.status(500).json({ success: false, error: 'Failed to fetch users.' });")
    lines.append("  }")
    lines.append("});")
    lines.append("")
    lines.append("router.get('/skill-paths', requireAdmin, async (_req: Request, res: Response) => {")
    lines.append("  try {")
    lines.append("    const [paths] = await pool.execute(")
    lines.append("      'SELECT sp.*, COUNT(sps.id) as step_count FROM skill_paths sp LEFT JOIN skill_path_steps sps ON sps.path_id = sp.id GROUP BY sp.id ORDER BY sp.created_at DESC'")
    lines.append("    ) as any[];")
    lines.append("    return res.json({ success: true, data: (Array.isArray(paths) ? paths : []).map((p: any) => ({")
    lines.append("      id: p.id, title: p.title, description: p.description, category: p.category,")
    lines.append("      totalSteps: p.step_count, estimatedHours: p.estimated_hours, icon: p.icon,")
    lines.append("      isActive: Boolean(p.is_active), createdAt: p.created_at,")
    lines.append("    }))});")
    lines.append("  } catch (err) {")
    lines.append("    logger.error('Admin get paths:', err);")
    lines.append("    return res.status(500).json({ success: false, error: 'Failed to fetch skill paths.' });")
    lines.append("  }")
    lines.append("});")
    lines.append("")
    lines.append("router.post('/skill-paths', requireAdmin, async (req: Request, res: Response) => {")
    lines.append("  try {")
    lines.append("    const { title, description, category, estimatedHours, icon } = req.body;")
    lines.append("    if (!title) return res.status(400).json({ success: false, error: 'Title is required.' });")
    lines.append("    const [r] = await pool.execute(")
    lines.append("      'INSERT INTO skill_paths (title, description, category, estimated_hours, icon, is_active, total_steps) VALUES (?, ?, ?, ?, ?, 1, 0)',")
    lines.append("      [title, description || null, category || 'development', estimatedHours || null, icon || 'Zap']")
    lines.append("    ) as any[];")
    lines.append("    return res.status(201).json({ success: true, data: { id: (r as any).insertId } });")
    lines.append("  } catch (err) {")
    lines.append("    logger.error('Create path:', err);")
    lines.append("    return res.status(500).json({ success: false, error: 'Failed to create skill path.' });")
    lines.append("  }")
    lines.append("});")
    lines.append("")
    lines.append("router.put('/skill-paths/:id', requireAdmin, async (req: Request, res: Response) => {")
    lines.append("  try {")
    lines.append("    const { title, description, category, estimatedHours, icon } = req.body;")
    lines.append("    if (!title) return res.status(400).json({ success: false, error: 'Title is required.' });")
    lines.append("    await pool.execute(")
    lines.append("      'UPDATE skill_paths SET title=?, description=?, category=?, estimated_hours=?, icon=? WHERE id=?',")
    lines.append("      [title, description || null, category || 'development', estimatedHours || null, icon || 'Zap', parseInt(req.params.id, 10)]")
    lines.append("    );")
    lines.append("    return res.json({ success: true });")
    lines.append("  } catch (err) {")
    lines.append("    logger.error('Update path:', err);")
    lines.append("    return res.status(500).json({ success: false, error: 'Failed to update skill path.' });")
    lines.append("  }")
    lines.append("});")
    lines.append("")
    lines.append("router.delete('/skill-paths/:id', requireAdmin, async (req: Request, res: Response) => {")
    lines.append("  try {")
    lines.append("    await pool.execute('UPDATE skill_paths SET is_active=0 WHERE id=?', [parseInt(req.params.id, 10)]);")
    lines.append("    return res.json({ success: true });")
    lines.append("  } catch (err) {")
    lines.append("    return res.status(500).json({ success: false, error: 'Failed to delete skill path.' });")
    lines.append("  }")
    lines.append("});")
    lines.append("")
    lines.append("router.get('/skill-paths/:pathId/steps', requireAdmin, async (req: Request, res: Response) => {")
    lines.append("  try {")
    lines.append("    const [rows] = await pool.execute(")
    lines.append("      'SELECT * FROM skill_path_steps WHERE path_id=? ORDER BY step_number ASC',")
    lines.append("      [parseInt(req.params.pathId, 10)]")
    lines.append("    ) as any[];")
    lines.append("    return res.json({ success: true, data: (Array.isArray(rows) ? rows : []).map((s: any) => ({")
    lines.append("      id: s.id, pathId: s.path_id, stepNumber: s.step_number,")
    lines.append("      title: s.title, description: s.description,")
    lines.append("      estimatedHours: s.estimated_hours,")
    lines.append("      videoUrl: s.video_url || null,")
    lines.append("      videoTitle: s.video_title || null,")
    lines.append("    }))});")
    lines.append("  } catch (err) {")
    lines.append("    return res.status(500).json({ success: false, error: 'Failed to fetch steps.' });")
    lines.append("  }")
    lines.append("});")
    lines.append("")
    lines.append("router.post('/skill-paths/:pathId/steps', requireAdmin, async (req: Request, res: Response) => {")
    lines.append("  try {")
    lines.append("    const pathId = parseInt(req.params.pathId, 10);")
    lines.append("    const { title, description, estimatedHours, videoUrl, videoTitle } = req.body;")
    lines.append("    if (!title) return res.status(400).json({ success: false, error: 'Title is required.' });")
    lines.append("    const [countRows] = await pool.execute(")
    lines.append("      'SELECT COUNT(*) as count FROM skill_path_steps WHERE path_id=?', [pathId]")
    lines.append("    ) as any[];")
    lines.append("    const stepNumber = ((Array.isArray(countRows) ? countRows : [])[0]?.count || 0) + 1;")
    lines.append("    const [r] = await pool.execute(")
    lines.append("      'INSERT INTO skill_path_steps (path_id, step_number, title, description, estimated_hours, video_url, video_title) VALUES (?, ?, ?, ?, ?, ?, ?)',")
    lines.append("      [pathId, stepNumber, title, description || null, estimatedHours || null, videoUrl || null, videoTitle || null]")
    lines.append("    ) as any[];")
    lines.append("    await pool.execute(")
    lines.append("      'UPDATE skill_paths SET total_steps=(SELECT COUNT(*) FROM skill_path_steps WHERE path_id=?) WHERE id=?',")
    lines.append("      [pathId, pathId]")
    lines.append("    );")
    lines.append("    return res.status(201).json({ success: true, data: { id: (r as any).insertId } });")
    lines.append("  } catch (err) {")
    lines.append("    logger.error('Create step:', err);")
    lines.append("    return res.status(500).json({ success: false, error: 'Failed to add step.' });")
    lines.append("  }")
    lines.append("});")
    lines.append("")
    lines.append("router.put('/skill-paths/:pathId/steps/:stepId', requireAdmin, async (req: Request, res: Response) => {")
    lines.append("  try {")
    lines.append("    const { title, description, estimatedHours, videoUrl, videoTitle } = req.body;")
    lines.append("    if (!title) return res.status(400).json({ success: false, error: 'Title is required.' });")
    lines.append("    await pool.execute(")
    lines.append("      'UPDATE skill_path_steps SET title=?, description=?, estimated_hours=?, video_url=?, video_title=? WHERE id=? AND path_id=?',")
    lines.append("      [title, description || null, estimatedHours || null, videoUrl || null, videoTitle || null, parseInt(req.params.stepId, 10), parseInt(req.params.pathId, 10)]")
    lines.append("    );")
    lines.append("    return res.json({ success: true });")
    lines.append("  } catch (err) {")
    lines.append("    logger.error('Update step:', err);")
    lines.append("    return res.status(500).json({ success: false, error: 'Failed to update step.' });")
    lines.append("  }")
    lines.append("});")
    lines.append("")
    lines.append("router.delete('/skill-paths/:pathId/steps/:stepId', requireAdmin, async (req: Request, res: Response) => {")
    lines.append("  try {")
    lines.append("    const pathId = parseInt(req.params.pathId, 10);")
    lines.append("    await pool.execute('DELETE FROM skill_path_steps WHERE id=? AND path_id=?', [parseInt(req.params.stepId, 10), pathId]);")
    lines.append("    await pool.execute('UPDATE skill_paths SET total_steps=(SELECT COUNT(*) FROM skill_path_steps WHERE path_id=?) WHERE id=?', [pathId, pathId]);")
    lines.append("    return res.json({ success: true });")
    lines.append("  } catch (err) {")
    lines.append("    logger.error('Delete step:', err);")
    lines.append("    return res.status(500).json({ success: false, error: 'Failed to delete step.' });")
    lines.append("  }")
    lines.append("});")
    lines.append("")
    lines.append("router.get('/opportunities', requireAdmin, async (_req: Request, res: Response) => {")
    lines.append("  try {")
    lines.append("    const [rows] = await pool.execute('SELECT * FROM opportunities ORDER BY created_at DESC') as any[];")
    lines.append("    return res.json({ success: true, data: (Array.isArray(rows) ? rows : []).map((o: any) => ({")
    lines.append("      id: o.id, title: o.title, company: o.company, description: o.description,")
    lines.append("      type: o.type, location: o.location, isRemote: Boolean(o.is_remote),")
    lines.append("      requiredSkills: safeSkills(o.required_skills),")
    lines.append("      experienceLevel: o.experience_level, applicationUrl: o.application_url,")
    lines.append("      deadline: o.deadline, isFeatured: Boolean(o.is_featured),")
    lines.append("      isActive: Boolean(o.is_active), createdAt: o.created_at,")
    lines.append("    }))});")
    lines.append("  } catch (err) {")
    lines.append("    logger.error('Admin opps:', err);")
    lines.append("    return res.status(500).json({ success: false, error: 'Failed to fetch opportunities.' });")
    lines.append("  }")
    lines.append("});")
    lines.append("")
    lines.append("const OppSchema = z.object({")
    lines.append("  title: z.string().min(1).max(500),")
    lines.append("  company: z.string().min(1).max(255),")
    lines.append("  description: z.string().min(1),")
    lines.append("  type: z.enum(['internship','freelance','part_time','full_time','apprenticeship']),")
    lines.append("  location: z.string().max(255).optional(),")
    lines.append("  isRemote: z.boolean().default(false),")
    lines.append("  requiredSkills: z.array(z.string()).optional(),")
    lines.append("  experienceLevel: z.string().max(100).optional(),")
    lines.append("  applicationUrl: z.string().max(1000).optional(),")
    lines.append("  deadline: z.string().optional().nullable(),")
    lines.append("  isFeatured: z.boolean().default(false),")
    lines.append("});")
    lines.append("")
    lines.append("router.post('/opportunities', requireAdmin, async (req: Request, res: Response) => {")
    lines.append("  try {")
    lines.append("    const parsed = OppSchema.safeParse(req.body);")
    lines.append("    if (!parsed.success) return res.status(400).json({ success: false, error: parsed.error.errors[0].message });")
    lines.append("    const d = parsed.data;")
    lines.append("    const [r] = await pool.execute(")
    lines.append("      'INSERT INTO opportunities (title,company,description,type,location,is_remote,required_skills,experience_level,application_url,deadline,is_featured,is_active) VALUES (?,?,?,?,?,?,?,?,?,?,?,1)',")
    lines.append("      [d.title,d.company,d.description,d.type,d.location||null,d.isRemote?1:0,d.requiredSkills?JSON.stringify(d.requiredSkills):null,d.experienceLevel||null,d.applicationUrl||null,d.deadline||null,d.isFeatured?1:0]")
    lines.append("    ) as any[];")
    lines.append("    return res.status(201).json({ success: true, data: { id: (r as any).insertId } });")
    lines.append("  } catch (err) {")
    lines.append("    logger.error('Admin create opp:', err);")
    lines.append("    return res.status(500).json({ success: false, error: 'Failed to create.' });")
    lines.append("  }")
    lines.append("});")
    lines.append("")
    lines.append("router.put('/opportunities/:id', requireAdmin, async (req: Request, res: Response) => {")
    lines.append("  try {")
    lines.append("    const parsed = OppSchema.safeParse(req.body);")
    lines.append("    if (!parsed.success) return res.status(400).json({ success: false, error: parsed.error.errors[0].message });")
    lines.append("    const d = parsed.data;")
    lines.append("    await pool.execute(")
    lines.append("      'UPDATE opportunities SET title=?,company=?,description=?,type=?,location=?,is_remote=?,required_skills=?,experience_level=?,application_url=?,deadline=?,is_featured=? WHERE id=?',")
    lines.append("      [d.title,d.company,d.description,d.type,d.location||null,d.isRemote?1:0,d.requiredSkills?JSON.stringify(d.requiredSkills):null,d.experienceLevel||null,d.applicationUrl||null,d.deadline||null,d.isFeatured?1:0,parseInt(req.params.id,10)]")
    lines.append("    );")
    lines.append("    return res.json({ success: true });")
    lines.append("  } catch (err) {")
    lines.append("    return res.status(500).json({ success: false, error: 'Failed to update.' });")
    lines.append("  }")
    lines.append("});")
    lines.append("")
    lines.append("router.put('/opportunities/:id/toggle', requireAdmin, async (req: Request, res: Response) => {")
    lines.append("  try {")
    lines.append("    const { isActive } = req.body;")
    lines.append("    await pool.execute('UPDATE opportunities SET is_active=? WHERE id=?', [isActive ? 1 : 0, parseInt(req.params.id, 10)]);")
    lines.append("    return res.json({ success: true });")
    lines.append("  } catch (err) {")
    lines.append("    return res.status(500).json({ success: false, error: 'Failed to toggle.' });")
    lines.append("  }")
    lines.append("});")
    lines.append("")
    lines.append("router.delete('/opportunities/:id', requireAdmin, async (req: Request, res: Response) => {")
    lines.append("  try {")
    lines.append("    await pool.execute('UPDATE opportunities SET is_active=0 WHERE id=?', [parseInt(req.params.id, 10)]);")
    lines.append("    return res.json({ success: true });")
    lines.append("  } catch (err) {")
    lines.append("    return res.status(500).json({ success: false, error: 'Failed to delete.' });")
    lines.append("  }")
    lines.append("});")
    lines.append("")
    lines.append("export default router;")

    content = "\n".join(lines)

    target = base / "server/src/routes/admin.ts"
    target.write_text(content, encoding="utf-8")
    print("  [OK] admin.ts completely rewritten - clean, no syntax errors")
    print("")
    print("Run: npm run dev")


if __name__ == "__main__":
    main()